name: Victor Rocks
favicon: null
layout_spectrum: 0.44962
typography_spectrum: 0.73479
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6466906529385597
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
